import * as katex from 'katex';

/**
 * MathML Converter & Sanitizer
 *
 * This module converts standard LaTeX expressions into robust, QTI-compliant
 * Presentation MathML using KaTeX, then strictly sanitizes the output
 * to prevent LMS parser failures (removing invisible nodes, semantic metadata, etc).
 */

/**
 * Configuration for KaTeX math rendering.
 */
const KATEX_OPTIONS = {
  throwOnError: false, // Don't crash on invalid LaTeX; render error as text
  output: 'mathml' as const,    // Force only MathML output
  strict: false        // Allow some non-strict LaTeX commonly generated by AI
};

/**
 * Escapes XML special characters for safe QTI embedding.
 */
export function escapeXmlForMath(text: string): string {
  if (text == null) return '';
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Strictly sanitizes generated MathML for QTI validity.
 * - Removes invisible operators.
 * - Strips all namespace prefixes (e.g., m:math -> math).
 * - Removes <semantics> and <annotation> tags, keeping only presentation MathML.
 * - Removes data-semantic-* and other non-standard attributes.
 * - Ensures root <math> tag has exactly the default MathML namespace.
 */
export function sanitizeMathML(mathml: string): string {
  if (!mathml) return mathml;

  let clean = mathml;

  // 1. Remove invisible operators
  clean = clean.replace(/&#x2061;|&#x2062;|&#8289;|&#8290;/g, '');

  // 2. Remove semantic elements but KEEP their contents if they wrap presentation math
  // Often engines output: <math><semantics><mrow>...</mrow><annotation>...</annotation></semantics></math>
  // We want to skip <semantics> and <annotation> but keep the <mrow> or other nodes inside.
  
  // First, remove <annotation> tags completely along with their content
  clean = clean.replace(/<annotation[^>]*>[\s\S]*?<\/annotation>/g, '');
  
  // Then, strip <semantics> tags but keep their inner content
  clean = clean.replace(/<semantics[^>]*>/g, '');
  clean = clean.replace(/<\/semantics>/g, '');

  // 3. Remove prefixes (e.g., <m:mrow> -> <mrow>, </m:math> -> </math>)
  clean = clean.replace(/<\/?[a-zA-Z0-9]+:([a-zA-Z0-9]+)/g, (match, tagName) => {
    return match.startsWith('</') ? `</${tagName}` : `<${tagName}`;
  });

  // 4. Remove all attributes except xmlns on the math tag
  // First, strip all data-semantic-* attributes
  clean = clean.replace(/\sdata-semantic-[a-zA-Z-]+="[^"]*"/g, '');
  
  // Remove other common attributes that break LMS rendering
  clean = clean.replace(/\s(class|style|id|display|encoding)="[^"]*"/g, '');

  // 5. Cleanup root <math> tag
  // Remove any existing xmlns or other attributes on <math> and set it strictly
  clean = clean.replace(/<math[^>]*>/, '<math xmlns="http://www.w3.org/1998/Math/MathML">');

  // 6. Final cleanup: empty mrow, whitespace
  clean = clean.replace(/<mrow>\s*<\/mrow>/g, '');
  clean = clean.replace(/>\s+</g, '><');

  return clean.trim();
}

/**
 * Removes LaTeX math delimiters and MathML blocks from text,
 * leaving only the textual content. Useful for XML attributes like 'title'.
 */
export function stripMath(text: string): string {
  if (!text) return '';
  
  // 1. Remove display math $$...$$
  let clean = text.replace(/\$\$[\s\S]*?\$\$/g, '');
  
  // 2. Remove escaped display math \[...\]
  clean = clean.replace(/\\\[[\s\S]*?\\\]/g, '');
  
  // 3. Remove escaped inline math \(...\)
  clean = clean.replace(/\\\([\s\S]*?\\\)/g, '');
  
  // 4. Remove simple inline math $...$
  clean = clean.replace(/\$[^$\n]+\$/g, '');
  
  // 5. Remove any existing MathML blocks <math>...</math>
  clean = clean.replace(/<math[^>]*>[\s\S]*?<\/math>/g, '');

  // 6. Clean up extra spaces
  return clean.replace(/\s+/g, ' ').trim();
}

/**
 * Detects whether a string contains standard LaTeX math blocks.
 * Supports: $...$, $$...$$, \(...\), \[...\]
 */
export function containsMath(text: string): boolean {
  if (!text) return false;
  const regex = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$[^$\n]+\$)/;
  return regex.test(text);
}

/**
 * Converts text containing LaTeX blocks into QTI-safe HTML/MathML.
 * Normal text is XML-escaped. LaTeX blocks are run through KaTeX and sanitized.
 */
export function convertTextWithMath(text: string): string {
  if (!text) return '';

  // Match LaTeX blocks:
  // $$ ... $$  (display math)
  // \[ ... \]  (display math)
  // \( ... \)  (inline math)
  // $ ... $    (inline math)
  const regex = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$[^$\n]+\$)/g;
  let lastIndex = 0;
  let result = '';
  let match;

  while ((match = regex.exec(text)) !== null) {
    // 1. Add XML-escaped text before the match
    if (match.index > lastIndex) {
      result += escapeXmlForMath(text.substring(lastIndex, match.index));
    }

    // 2. Process the matched Math block
    const mathBlock = match[0];
    let isDisplayMode = false;
    let pureLatex = '';

    if (mathBlock.startsWith('$$')) {
      isDisplayMode = true;
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('\\[')) {
      isDisplayMode = true;
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('\\(')) {
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('$')) {
      pureLatex = mathBlock.substring(1, mathBlock.length - 1);
    }
    
    // KaTeX sometimes fails on pure newlines if not handled carefully
    pureLatex = pureLatex.trim();

    try {
      // Ensure katex is available (defensive check)
      if (!katex) {
        throw new Error("KaTeX library not loaded");
      }

      // Use KaTeX to render LaTeX -> raw MathML
      const renderFn = (katex as any).renderToString || (katex as any).default?.renderToString;
      if (!renderFn) {
        throw new Error("KaTeX renderToString function not found");
      }

      const rawHtml = renderFn(pureLatex, {
        ...KATEX_OPTIONS,
        displayMode: isDisplayMode
      });

      // KaTeX outputs HTML containing <span class="katex-mathml"><math>...</math></span>
      // We extract ONLY the <math>...</math> tree for QTI compliance
      const mathmlExec = /<math[^>]*>[\s\S]*?<\/math>/.exec(rawHtml);
      
      if (mathmlExec && mathmlExec[0]) {
        // Run the extracted MathML through our strict sanitizer
        const safeMathMl = sanitizeMathML(mathmlExec[0]);
        result += safeMathMl;
      } else {
        // Fallback: If no MathML was generated, just escape the raw latex back
        result += escapeXmlForMath(mathBlock);
      }
    } catch (e) {
      console.warn("KaTeX rendering error for:", pureLatex, e);
      // Fallback on error: escape raw latex text
      result += escapeXmlForMath(mathBlock);
    }

    lastIndex = regex.lastIndex;
  }

  // 3. Add trailing text
  if (lastIndex < text.length) {
    result += escapeXmlForMath(text.substring(lastIndex));
  }

  return result;
}

/**
 * Wrap converted text in a QTI `<p>` element.
 */
export function createQTIParaWithMath(text: string): string {
  const converted = convertTextWithMath(text);
  return `<p>${converted}</p>`;
}

/**
 * Converts math within an existing XML/HTML string without escaping the outer tags.
 * Use this for processing full XML blocks where you don't want to break the structure.
 */
export function processXmlMath(xml: string): string {
  if (!xml) return '';
  
  const regex = /(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\)|\$[^$\n]+\$)/g;
  let lastIndex = 0;
  let result = '';
  let match;

  while ((match = regex.exec(xml)) !== null) {
    // 1. Add non-math part AS IS (don't escape XML)
    if (match.index > lastIndex) {
      result += xml.substring(lastIndex, match.index);
    }

    // 2. Process math block (re-use convertTextWithMath logic for the block)
    const mathBlock = match[0];
    let isDisplayMode = false;
    let pureLatex = '';

    if (mathBlock.startsWith('$$')) {
      isDisplayMode = true;
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('\\[')) {
      isDisplayMode = true;
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('\\(')) {
      pureLatex = mathBlock.substring(2, mathBlock.length - 2);
    } else if (mathBlock.startsWith('$')) {
      pureLatex = mathBlock.substring(1, mathBlock.length - 1);
    }
    
    pureLatex = pureLatex.trim();

    try {
      if (!katex) throw new Error("KaTeX library not loaded");
      const renderFn = (katex as any).renderToString || (katex as any).default?.renderToString;
      const rawHtml = renderFn(pureLatex, { ...KATEX_OPTIONS, displayMode: isDisplayMode });
      const mathmlExec = /<math[^>]*>[\s\S]*?<\/math>/.exec(rawHtml);
      
      if (mathmlExec && mathmlExec[0]) {
        result += sanitizeMathML(mathmlExec[0]);
      } else {
        result += mathBlock; // No escaping needed for XML blocks
      }
    } catch (e) {
      result += mathBlock;
    }

    lastIndex = regex.lastIndex;
  }

  if (lastIndex < xml.length) {
    result += xml.substring(lastIndex);
  }

  return result;
}

/**
 * Wrap converted text in a QTI `<simpleChoice>` element.
 */
export function createQTIChoiceWithMath(
  text: string,
  identifier: string
): string {
  const converted = convertTextWithMath(text);
  return `<simpleChoice identifier="${identifier}">${converted}</simpleChoice>`;
}

// ── Obsolete MathJax Stubs (for backwards compat if needed elsewhere) ──

export function setQtiMathMode(_mode: 'default' | 'mathml'): void {
  // intentionally empty
}

export function ensureMathJax(): Promise<any> {
  return Promise.resolve(null);
}
